### ISSUE TITLE
Facing issues with the extrinsic matrix and the projections

### ISSUE THREAD

**Issue by devadharshini97** [DoongLi/livox_camera_lidar_calibration_d2#1]
Hey!
I am using a livox mid-360 lidar and am trying to do the lidar-camera calibration. But, the error output from extrinsic matrix 1 and 2 are higher than the threshold. But still, I tried the projection of lidar on camera images, but it is not getting projected. Any idea how to solve this? I am not sure how I can evaluate this extrinsic matrix. Any help is much appreciated. Thank you!

**Comment by DoongLi** [comment]
Are you using my repo? This method often does not iterate the final result.

**Comment by devadharshini97** [comment]
Yes, I am using this repo....I see...i have the point cloud and the images from the camera. I am getting errors for the extrinsic matrix conversion and the projection results doesn't show any point clouds on the images. Do you know of any other repos that I can follow for this ? -> I am using Livox mid 360 lidar and mapir RGN wide camera.

**Comment by DoongLi** [comment]
I think you can use OpenCalib. When the camera and livox pose differ considerably,  **livox camera lidar calibration** iterative calculation may not converge.

**Comment by DoongLi** [comment]
Code: https://github.com/PJLab-ADG/SensorsCalibration

Paper: OpenCalib: A Multi-sensor Calibration Toolbox for Autonomous Driving

**Comment by devadharshini97** [comment]
Thanks a lot I will check that out.
